### ISSUE TITLE
I'm getting Accesory Not Supported in Homeapp

### ISSUE THREAD

**Issue by CyberMrProper** [grzegorz914/homebridge-melcloud-control#1]
Not sure if the plugin is finished or work in progress, but I just wanted to highlight that after configuring it and restarting homebridge the accessory is no being recognised properly in home app.
![IMG_8345](https://user-images.githubusercontent.com/63667331/174269846-83cb3851-62f6-4435-abe0-6c6590f4a852.jpeg)

**Comment by grzegorz914** [comment]
it is in test phase right now, 0.0.3-beta is available

**Comment by CyberMrProper** [comment]
Nice, for me it is not working. Even with the latest beta, I checked the log and the last line is "debug devicesListData: " + full json from the response. Then nothing, no error no additional logs.

**Comment by grzegorz914** [comment]
work in progress, any test appreciated

**Comment by CyberMrProper** [comment]
I got what is happening, my API return json is as follows:

 "Structure": {
      "Floors": [],
      "Areas": [],
      "Devices": [
        {
          "DeviceID": 131935,
          "DeviceName": "Aire",
.....

In your response parsing code, you are expecting them to be nested, buildingStructure.Floors[j].Areas[k].Devices, but in my configuration that is not the case. Let me know if you need additional info.

**Comment by grzegorz914** [comment]
Please try 0.0.5-beta.11 and let me know

**Comment by CyberMrProper** [comment]
Still no luck:

[6/18/2022, 2:54:00 PM] [homebridge-melcloud-control] Account: Test, Update devices list error: TypeError: Cannot read properties of undefined (reading 'Model')

**Comment by grzegorz914** [comment]
Ah ok, try again beta 14

**Comment by CyberMrProper** [comment]
I was able to add it to HK! Tried really quick, heatercooler accessory current configured temperature is not correct, also the following error is coming in the log

[6/18/2022, 4:25:21 PM] [homebridge-melcloud-control] This plugin generated a warning from the characteristic 'Heating Threshold Temperature': characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics. See https://homebridge.io/w/JtMGR for more info.
[6/18/2022, 4:25:21 PM] [homebridge-melcloud-control] Error: 
    at HeatingThresholdTemperature.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2142:105)
    at HeatingThresholdTemperature.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1990:14)
    at HeatingThresholdTemperature.Characteristic.updateValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1457:20)
    at HeaterCooler.Service.updateCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:481:35)
    at melCloudDevice.updateDevicesState (/usr/local/lib/node_modules/homebridge-melcloud-control/index.js:392:8)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by grzegorz914** [comment]
This error is from MELCloud service, check the setting for heating threshold in MELCloud device setting

**Comment by CyberMrProper** [comment]
Not sure, I think you are not picking the right param from the configured temp in the API. In cool mode: mine reports 21 in HK, but it's actually set to 24 in the device.

**Comment by grzegorz914** [comment]
please try beta22 and also look here
![IMG_0609](https://user-images.githubusercontent.com/28867813/174444047-364b4dbb-aca1-4020-ba48-29988b1c9ab9.jpg)
:

**Comment by grzegorz914** [comment]
I have set limit for CoolingThresholdTemperature min 16 and max 31,
for HeatingThresholdTemperature min 10 and max 31, sam as in MELCloud settings

**Comment by CyberMrProper** [comment]
In my device, current configured target temperature (cool or heat) is coming in property Devices.Device.SetTemperature.

**Comment by grzegorz914** [comment]
please try 0.0.5

**Comment by grzegorz914** [comment]
I think all is fixed in 0.0.6

**Comment by CyberMrProper** [comment]
Looking much better now, thanks for your work! 

Still getting warning on null value for HeatingThresholdTemperature, I think the following line:

[const value = deviceState.DefaultHeatingSetTemperature;] https://github.com/grzegorz914/homebridge-melcloud-control/blob/1bc8359d27544373a1bf1520089334850b537f0e/index.js#L767

should be [const value = deviceState.SetTemperature;] since mine devices uses the same setting for heat and cool values.

There are some additional fixes that are nice to have, such as my device has Device.SwingFunction: false, so it means heatercooler shouldn't have Oscillate characteristic in HK. Then I see some more weird behaviour with the fan function. Let me know how you prefer me to report it.

**Comment by grzegorz914** [comment]
thanks fixed in 0.0.7
