### ISSUE TITLE
Changing the fan speed and then playing with auto/cool is still unconsistent

### ISSUE THREAD

**Issue by CyberMrProper** [grzegorz914/homebridge-melcloud-control#139]
Attaching a video of the behaviour: 

https://github.com/user-attachments/assets/e44bb36b-5ffa-4c1b-9519-9c77cdaa05b4

I don't see anything weird in the logs

**Comment by grzegorz914** [comment]
this is already fixed in 3.0.4

**Comment by grzegorz914** [comment]
sorry was mistake, in 3.0.5 is fixed

**Comment by CyberMrProper** [comment]
Mmm still happening to me in 3.0.5, the undefined is gone in the log. But the reversion to AUTO is still there.

**Comment by CyberMrProper** [comment]
I'm attaching the log, have in mind that in the log COOL is always reported, but in the UI at some point it reverts to AUTO (as in the video)

[homebridge-melcloud-control.log.txt](https://github.com/user-attachments/files/16800561/homebridge-melcloud-control.log.txt)

**Comment by grzegorz914** [comment]
arę you set correct mode in config

**Comment by grzegorz914** [comment]
3.0.6-beta.0

**Comment by CyberMrProper** [comment]
Something is weird, in the UI config I have

<img width="708" alt="Screenshot 2024-08-29 at 4 36 10 PM" src="https://github.com/user-attachments/assets/9f538a4f-8b71-44dd-9cd5-871df884168e">

but in the json

 "ataDevices": [
                        {
                            "id": 131935,
                            "type": 0,
                            "name": "Aire",
                            "displayMode": 1,
                            "heatDryFanMode": 1,
                            "coolDryFanMode": 1,
                            "autoDryFanMode": 1,
                            "presets": false,
                            "temperatureSensor": false,
                            "temperatureSensorOutdoor": false,
                            "buttonsSensors": [
                                {
                                    "displayType": 0,
                                    "namePrefix": false
                                }
                            ]
                        }

**Comment by grzegorz914** [comment]
try 3.0.6-beta.0 and let me know

**Comment by CyberMrProper** [comment]
Still happening

**Comment by grzegorz914** [comment]
ok try beta 1

**Comment by CyberMrProper** [comment]
Yeah!! now the issue is gone. Thank you so much!
