### ISSUE TITLE
Can't configure anything for A/C

### ISSUE THREAD

**Issue by markwwd** [grzegorz914/homebridge-melcloud-control#147]
The latest version of plugin v3.1.3 and Homebridge v2.0.0 Beta 15

I can't seem to configure anything regarding Air Conditioner. There are no settings.

I've tried reverting back to old versions and I can't seem to retrieve settings there either.

![image](https://github.com/user-attachments/assets/7386fcdd-71e5-4121-8de5-3c27b822984d)

**Comment by grzegorz914** [comment]
You need first connects to melcloud on the first screen

**Comment by markwwd** [comment]
I did all that. It used to work already now it doesn't seem to anymore.

**Comment by grzegorz914** [comment]
Fixed, please u-datę and login again

**Comment by grzegorz914** [comment]
Sorry for this mistake, today was very bad day for me.

**Comment by markwwd** [comment]
It still doesn't show the settings.

![image](https://github.com/user-attachments/assets/127265cb-f69f-42bf-a47d-2385a3e53eb2)

**Comment by grzegorz914** [comment]
After you press login to melcloud what is displayed as info?

**Comment by markwwd** [comment]
Only this:
![image](https://github.com/user-attachments/assets/4a748e86-fa1e-4744-8dc2-c63b4b3b70f1)

**Comment by grzegorz914** [comment]
![IMG_1010](https://github.com/user-attachments/assets/0c6ce518-d490-4cc2-8cee-4f889c83a6cc)

**Comment by markwwd** [comment]
When I press that it shows "No new devices found."

**Comment by grzegorz914** [comment]
Are you updated to 3.1.5

**Comment by markwwd** [comment]
Yes, 3.1.5

**Comment by grzegorz914** [comment]
Post the config.json please

**Comment by markwwd** [comment]
`{
    "accounts": [
        {
            "name": "***********",
            "user": "**********",
            "passwd": "************",
            "language": "0",
            "ataDevices": [
                {
                    "displayMode": 0,
                    "heatDryFanMode": 1,
                    "autoDryFanMode": 1,
                    "temperatureSensor": false,
                    "temperatureSensorOutdoor": false,
                    "presets": [
                        {
                            "displayType": 0,
                            "namePrefix": false
                        },
                        {
                            "id": 495256,
                            "name": "Ogrevanje",
                            "displayType": 0,
                            "namePrefix": false
                        },
                        {
                            "id": 525120,
                            "name": "Zračenje",
                            "displayType": 0,
                            "namePrefix": false
                        },
                        {
                            "id": 524976,
                            "name": "Hlajenje",
                            "displayType": 0,
                            "namePrefix": false
                        }
                    ],
                    "buttonsSensors": [
                        {
                            "displayType": 0,
                            "namePrefix": false
                        }
                    ]
                },
                {
                    "id": 91818182,
                    "type": 0,
                    "typeString": "Air Conditioner",
                    "name": "AIR CONDITIONER",
                    "displayMode": 1,
                    "heatDryFanMode": 1,
                    "coolDryFanMode": 1,
                    "autoDryFanMode": 1,
                    "temperatureSensor": false,
                    "temperatureSensorOutdoor": false,
                    "presets": [
                        {
                            "displayType": 0,
                            "namePrefix": false
                        },
                        {
                            "SetTemperature": 22,
                            "Power": true,
                            "OperationMode": 1,
                            "VaneHorizontal": 1,
                            "VaneVertical": 0,
                            "FanSpeed": 0,
                            "ID": 495256,
                            "Client": 79190,
                            "DeviceLocation": 91818182,
                            "Number": 1,
                            "Configuration": "<settings><st>22</st><pw>true</pw><om>1</om><vd>0</vd><hd>1</hd><fs>0</fs></settings>",
                            "NumberDescription": "Ogrevanje",
                            "id": 495256,
                            "name": "Ogrevanje",
                            "namePrefix": false
                        },
                        {
                            "SetTemperature": 16,
                            "Power": true,
                            "OperationMode": 7,
                            "VaneHorizontal": 1,
                            "VaneVertical": 0,
                            "FanSpeed": 0,
                            "ID": 525120,
                            "Client": 79190,
                            "DeviceLocation": 91818182,
                            "Number": 2,
                            "Configuration": "<settings><st>16</st><pw>true</pw><om>7</om><vd>0</vd><hd>1</hd><fs>0</fs></settings>",
                            "NumberDescription": "Zračenje",
                            "id": 525120,
                            "name": "Zračenje",
                            "namePrefix": false
                        },
                        {
                            "SetTemperature": 23,
                            "Power": true,
                            "OperationMode": 3,
                            "VaneHorizontal": 1,
                            "VaneVertical": 0,
                            "FanSpeed": 0,
                            "ID": 524976,
                            "Client": 79190,
                            "DeviceLocation": 91818182,
                            "Number": 3,
                            "Configuration": "<settings><st>23</st><pw>true</pw><om>3</om><vd>0</vd><hd>1</hd><fs>0</fs></settings>",
                            "NumberDescription": "Hlajenje",
                            "id": 524976,
                            "name": "Hlajenje",
                            "namePrefix": false
                        }
                    ],
                    "buttonsSensors": [
                        {
                            "displayType": 0,
                            "namePrefix": false
                        }
                    ]
                }
            ],
            "atwDevices": [
                {
                    "displayMode": 1,
                    "temperatureSensor": false,
                    "temperatureSensorFlow": false,
                    "temperatureSensorReturn": false,
                    "temperatureSensorFlowZone1": false,
                    "temperatureSensorReturnZone1": false,
                    "temperatureSensorFlowWaterTank": false,
                    "temperatureSensorReturnWaterTank": false,
                    "temperatureSensorFlowZone2": false,
                    "temperatureSensorReturnZone2": false,
                    "presets": [
                        {
                            "displayType": 0,
                            "namePrefix": false
                        }
                    ],
                    "buttonsSensors": [
                        {
                            "displayType": 0,
                            "namePrefix": false
                        }
                    ]
                }
            ],
            "ervDevices": [
                {
                    "displayMode": 1,
                    "temperatureSensor": false,
                    "temperatureSensorOutdoor": false,
                    "temperatureSensorSupply": false,
                    "presets": [
                        {
                            "displayType": 0,
                            "namePrefix": false
                        }
                    ],
                    "buttonsSensors": [
                        {
                            "displayType": 0,
                            "namePrefix": false
                        }
                    ]
                }
            ],
            "refreshInterval": 60,
            "deviceRefreshInterval": 1,
            "enableDebugMode": false,
            "disableLogInfo": false,
            "disableLogDeviceInfo": false,
            "restFul": {
                "enable": false,
                "debug": false
            },
            "mqtt": {
                "enable": false,
                "debug": false,
                "auth": false
            }
        }
    ],
    "platform": "melcloudcontrol"
}`

**Comment by grzegorz914** [comment]
The config is wrong, do not make it manually, remove all objects from ataDevices, atwDevices, ervDevices, leave only ataDevices[], atwDevices[], ervDevices[]. Save and login again. All we’ll be created automatically

**Comment by markwwd** [comment]
I didn't manually configure it.. idk why it did that.

It now works! Thanks!
