### ISSUE TITLE
Accessory not responding

### ISSUE THREAD

**Issue by Mr-Colorist** [grzegorz914/homebridge-melcloud-control#3]
Hi!

I succefully added my Ducted AC and I can perfectly control it on the Homebridge's accessories page. 

The problem I have is when in the Home App, I can add the Air conditioner as an accessory (sometimes I see the correct info like room temperature or if it's on or off for just a few seconds) and shorty after this, It isn't responding on the Home App. If I remove it from there, to add it again, I have to go to ./homebridge/persist. and remove the files to add it again (If I don't remove the files It's impossible to add it again on the app).

How can I fix it? I don't know what else to do. Do I have to config anything on my router to make it work? Please I need your help.

Thank you so much for this fantastic plugin.

Kind regards

**Comment by grzegorz914** [comment]
what a vision You use?

**Comment by grzegorz914** [comment]
I have the same Behavioir if try control from Home.app, very strange. Will check it this asap.

**Comment by grzegorz914** [comment]
fixed

**Comment by Mr-Colorist** [comment]
Sorry but still not working. When I add it to the Home app I can see the status of the AC but then I can't change anything, ON/OFF, temperature, etc. It says isn't responding. So weird because, as I said, I can control it with Homebridge.

I really appreaciate your help and for creating this awesome plugin. I hope you can make it work on the Home App. Thank you

**Comment by grzegorz914** [comment]
This must be something wrong in your local environment, on my side working like a harm.

https://user-images.githubusercontent.com/28867813/175779842-9061f7e4-9624-47cb-811c-6c157c739b72.MOV

**Comment by Mr-Colorist** [comment]
Then I don't know how to fix it T.T. I have Homebridge installed on my Synology NAS.

**Comment by grzegorz914** [comment]
Are you using other homebridge MELCloud plugin? Are you updated to latest version and read the note? Can you enabler debug and get any error in the log?
